package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'DeployStaging'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("DeployStaging")) {
    dependencies {
        expect(RelativeId("BuildWebsite")) {
            artifacts {
                cleanDestination = true
                artifactRules = "+:website"
            }
        }
        update(RelativeId("BuildWebsite")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:website"
            }
        }

    }
}
